options:
    target:
        type: string
        description: 'ISCSI target IP'
        default: 
    port:
        type: string
        description: 'ISCSI target port'
        default:
    initiator-dictionary:
        type: string
        default: '{}'
        description: |
            Dictionary of hostnames (fqdn) and initiator names, surrounded by 
            single quotes. The charm compares the machine hostname to 
            the list, and provide the correct initiator associated to 
            it. If not defined, the initiator name will be provided 
            randomly. Format : 
            '{"hostname1": "iqn.yyyy-mm.naming-authority:uniquename1",
              "hostname2": "iqn.yyyy-mm.naming-authority:uniquename2}'
    multipath-conf-devices:
        type: string
        default:
        description: |
            In multipath.conf, add a device specific configuration. String should be of 
            json dictionary format. Example: 
                value : '{"vendor":"PURE","product": "FlashArray","fast_io_fail_tmo": "10", "path_grouping_policy":"group_by_prio"}'
                will produce this configuration:
                device {
                    vendor "PURE"
                    product "FlashArray"
                    fast_io_fail_tmo 10
                    path_grouping_policy "group_by_prio"
                }
    iscsi-node-startup:
        type: string
        default: automatic
        description: Startup setting for sessions. Either automatic or manual
    iscsi-node-session-iscsi-fastabort:
        type: string
        default: 'Yes'
    iscsi-node-session-scan:
        type: string
        default: auto
        description: Automatic scans are performed on startup, on login, and on AEN/AER reception on devices supporting it.
