options:
    target:
        type: string
        description: 'ISCSI target IP'
        default: pouet
    port:
        type: string
        description: 'ISCSI target port'
        default:
    iscsid-conf:
        type: string
        default:
        description: |
            To input a complete configuration in /etc/iscsi/iscsid.conf,
            use a json formatted string here.
    initiator-dictionary:
        type: string
        default: '{}'
        description: |
            Dictionary of hostnames (fqdn) and initiator names, surrounded by 
            single quotes. The charm compares the machine hostname to 
            the list, and provide the correct initiator associated to 
            it. If not defined, the initiator name will be provided 
            randomly. Format : 
            '{"hostname1": "iqn.yyyy-mm.naming-authority:uniquename1", 
              "hostname2": "iqn.yyyy-mm.naming-authority:uniquename2}'
    multipath-conf:
        type: string
        default:
        description: |
            To input a complete configuration in /etc/multipath.conf,
            use a json formatted string here.
    