options:
    target:
        type: string
        description: 'ISCSI target IP'
        default:
    port:
        type: string
        description: 'ISCSI target port'
        default:
    iscsid-conf:
        type: string
        default:
        description: |
        To input a complete configuration in /etc/iscsi/iscsid.conf,
        use a json formatted string here.
    multipath-conf:
        type: string
        default:
        description: |
        To input a complete configuration in /etc/multipath.conf,
        use a json formatted string here.
